version: '3.7'
services:
  api:
    container_name: api
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.60'
          memory: 512M
        reservations:
          cpus: '0.30'
          memory: 256M
    build:
      context: ./src/backend/
      dockerfile: Dockerfile
    image: api:latest
    ports:
      - "8844:8844"
    command: gunicorn -w 1 -b :8844 backend.app:app
  ui:
    container_name: ui
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: 512M
        reservations:
          cpus: '0.20'
          memory: 128M
    build:
      context: ./src/frontend/
      dockerfile: Dockerfile
    image: ui:latest
    ports:
      - "80:80"
    depends_on:
      - api
    links:
      - api:cronus.altobyte

