apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronus-ui
spec:
  selector:
    matchLabels:
      app: cronus-ui
  replicas: 2
  template:
    metadata:
      labels:
        app: cronus-ui
    spec:
      containers:
      - name: cronus-ui
        image: cronus-ui
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000